package nedu.edsn.service.p4._2.standard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-07T17:34:06.513+07:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "urn:nedu:edsn:service:p4:2:standard", name = "P4PortType")
@XmlSeeAlso({edsn.edsn.data.soapfault._1.standard.ObjectFactory.class, nedu.edsn.data.p4collecteddatabatchrequest._2.standard.ObjectFactory.class, nedu.edsn.data.p4collecteddatabatchresultrequest._2.standard.ObjectFactory.class, nedu.edsn.data.p4collecteddatabatchresponse._2.standard.ObjectFactory.class, nedu.edsn.data.p4collecteddatabatchresultresponse._2.standard.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface P4PortType {

    @WebMethod(operationName = "P4CollectedDataBatchRequest", action = "urn:P4CollectedDataBatchRequest")
    @WebResult(name = "P4CollectedDataBatchResponseEnvelope", targetNamespace = "urn:nedu:edsn:data:p4collecteddatabatchresponse:2:standard", partName = "part1")
    public nedu.edsn.data.p4collecteddatabatchresponse._2.standard.P4CollectedDataBatchResponseEnvelope p4CollectedDataBatchRequest(

        @WebParam(partName = "part1", name = "P4CollectedDataBatchRequestEnvelope", targetNamespace = "urn:nedu:edsn:data:p4collecteddatabatchrequest:2:standard")
        nedu.edsn.data.p4collecteddatabatchrequest._2.standard.P4CollectedDataBatchRequestEnvelope part1
    ) throws SOAPFault;

    @WebMethod(operationName = "P4CollectedDataBatchResultRequest", action = "urn:P4CollectedDataBatchResultRequest")
    @WebResult(name = "P4CollectedDataBatchResultResponseEnvelope", targetNamespace = "urn:nedu:edsn:data:p4collecteddatabatchresultresponse:2:standard", partName = "part1")
    public nedu.edsn.data.p4collecteddatabatchresultresponse._2.standard.P4CollectedDataBatchResultResponseEnvelope p4CollectedDataBatchResultRequest(

        @WebParam(partName = "part1", name = "P4CollectedDataBatchResultRequestEnvelope", targetNamespace = "urn:nedu:edsn:data:p4collecteddatabatchresultrequest:2:standard")
        nedu.edsn.data.p4collecteddatabatchresultrequest._2.standard.P4CollectedDataBatchResultRequestEnvelope part1
    ) throws SOAPFault;
}
